variables:
  GIT_SUBMODULE_STRATEGY: normal
image : mcr.microsoft.com/dotnet/core/sdk:latest
stages:
  - build
build:
 stage: build
 tags: 
  - build
  - docker
 script:
  - 'dotnet restore'
  - 'dotnet publish -o publish/rfpproxy -c Release RfpProxy/RfpProxy.csproj'
  - 'dotnet publish -o publish/rfpproxy.log -c Release RfpProxy.Log/RfpProxy.Log.csproj'
  - 'dotnet publish -o publish/rfpproxy.pcap -c Release RfpProxy.Pcap/RfpProxy.Pcap.csproj'
  - 'dotnet publish -o publish/rfpproxy.inject -c Release RfpProxy.Inject/RfpProxy.Inject.csproj'
  - 'dotnet publish -o publish/rfpproxy.led -c Release RfpProxy.ChangeLed/RfpProxy.ChangeLed.csproj'
  - 'dotnet publish -o publish/rfpproxy.traffic -c Release RfpProxy.Traffic/RfpProxy.Traffic.csproj'
  - 'dotnet publish -o publish/compressipui -c Release CompressIPUI/CompressIPUI.csproj'
  - 'dotnet publish -o publish/avm -c Release AVM/AVM.csproj'
  - 'dotnet publish -o publish/busyled -c Release BusyLed/BusyLed.csproj'
  - 'dotnet publish -o publish/midi -c Release MediaTone/MediaTone.csproj'
  - 'dotnet publish -o publish/morseled -c Release MorseLed/MorseLed.csproj'
  - 'dotnet publish -o publish/virtualrfp -c Release SoftRfp/SoftRfp.csproj'
  - 'apt update -y'
  - 'apt install -y rpm'
  - 'rpmbuild --target noarch --define "_binaries_in_noarch_packages_terminate_build 0" -bb --build-in-place rpmbuild/SPECS/rfpproxy.spec'
 artifacts:
  paths:
  - publish
  - rpm