stages:
  - build
  - deploy
build:
 stage: build
 tags: 
  - dotnet
 script:
  - 'dotnet add RfpProxy/RfpProxy.csproj package Microsoft.Packaging.Tools.Trimming -v 1.1.0-preview1-26619-01'
  - 'dotnet restore'
  - 'dotnet publish -o publish -c Release --self-contained -r linux-x64 /p:TrimUnusedDependencies=true RfpProxy/RfpProxy.csproj'
 only:
  - master
 artifacts:
  paths:
  - publish
deploy:
 stage: deploy
 when: manual
 tags: 
  - guru
 dependencies:
  - build
 script:
  - 'rsync -av --delete publish/ /opt/rfpproxy/'
  - '/bin/chmod +x /opt/rfpproxy/RfpProxy'
  - 'sudo /bin/systemctl restart rfpproxy'
 only:
  - master