variables:
  GIT_SUBMODULE_STRATEGY: normal
stages:
  - build
  - deploy
  - deploy-proxy
build:
 stage: build
 tags: 
  - build
  - dotnet
 script:
  - 'dotnet restore'
  - 'dotnet publish -o publish/rfpproxy -c Release RfpProxy/RfpProxy.csproj'
  - 'dotnet publish -o publish/rfpproxy.log -c Release RfpProxy.Log/RfpProxy.Log.csproj'
  - 'dotnet publish -o publish/rfpproxy.pcap -c Release RfpProxy.Pcap/RfpProxy.Pcap.csproj'
  - 'dotnet publish -o publish/rfpproxy.inject -c Release RfpProxy.Inject/RfpProxy.Inject.csproj'
  - 'dotnet publish -o publish/rfpproxy.led -c Release RfpProxy.ChangeLed/RfpProxy.ChangeLed.csproj'
  - 'dotnet publish -o publish/rfpproxy.traffic -c Release RfpProxy.Traffic/RfpProxy.Traffic.csproj'
  - 'dotnet publish -o publish/compressipui -c Release CompressIPUI/CompressIPUI.csproj'
  - 'dotnet publish -o publish/avm -c Release AVM/AVM.csproj'
  - 'dotnet publish -o publish/busyled -c Release BusyLed/BusyLed.csproj'
  - 'dotnet publish -o publish/midi -c Release MediaTone/MediaTone.csproj'
 only:
  - master
 artifacts:
  paths:
  - publish
deploy:
 stage: deploy
 tags: 
  - deploy
  - omm
 dependencies:
  - build
 script:
  - 'rsync -av --delete --exclude rfpproxy publish/ /opt/rfpproxy/'
 only:
  - master
deploy-proxy:
 stage: deploy-proxy
 when: manual
 tags: 
  - deploy
  - omm
 dependencies:
  - build
 script:
  - 'rsync -av --delete publish/rfpproxy/ /opt/rfpproxy/rfpproxy/'
  - 'sudo /sbin/setcap CAP_NET_ADMIN=+eip /opt/rfpproxy/rfpproxy/rfpproxy'
  - 'sudo /usr/bin/systemctl restart rfpproxy'
 only:
  - master