name: dotnet publish workflow
on: [workflow_dispatch, push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
    - run: 'dotnet restore'
    - run: 'dotnet publish -o publish/rfpproxy -c Release RfpProxy/RfpProxy.csproj'
    - run: 'dotnet publish -o publish/rfpproxy.log -c Release RfpProxy.Log/RfpProxy.Log.csproj'
    - run: 'dotnet publish -o publish/rfpproxy.pcap -c Release RfpProxy.Pcap/RfpProxy.Pcap.csproj'
    - run: 'dotnet publish -o publish/rfpproxy.inject -c Release RfpProxy.Inject/RfpProxy.Inject.csproj'
    - run: 'dotnet publish -o publish/rfpproxy.led -c Release RfpProxy.ChangeLed/RfpProxy.ChangeLed.csproj'
    - run: 'dotnet publish -o publish/rfpproxy.traffic -c Release RfpProxy.Traffic/RfpProxy.Traffic.csproj'
    - run: 'dotnet publish -o publish/compressipui -c Release CompressIPUI/CompressIPUI.csproj'
    - run: 'dotnet publish -o publish/avm -c Release AVM/AVM.csproj'
    - run: 'dotnet publish -o publish/busyled -c Release BusyLed/BusyLed.csproj'
    - run: 'dotnet publish -o publish/midi -c Release MediaTone/MediaTone.csproj'
    - run: 'dotnet publish -o publish/morseled -c Release MorseLed/MorseLed.csproj'
    - run: 'dotnet publish -o publish/virtualrfp -c Release SoftRfp/SoftRfp.csproj'
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: rfpproxy_publish
        path: publish
    - run: 'sudo apt install rpm'
    - run: 'rpmbuild --target noarch --define "_binaries_in_noarch_packages_terminate_build 0" -bb --build-in-place rpmbuild/SPECS/rfpproxy.spec'
    - name: Upload rpm
      uses: actions/upload-artifact@v2
      with:
        name: rpm
        path: rpm/*.rpm
